const nodemailer = require('nodemailer');

exports.sentOTPVerificaiton = (message) => {
    /* const transporter = nodemailer.createTransport({
      host: 'smtp.ethereal.email',
      port: 587,
      auth: {
        user: 'dayne.ledner75@ethereal.email',
        pass: 'wE9RW81FZW7ZREhQcw',
      },
    }); */
    const transporter = nodemailer.createTransport({
        host: "smtp.mailtrap.io",
        port: 2525,
        auth: {
            user: "74bcc23ab3fe72", //generated by Mailtrap
            pass: "792d6aa61c99b5" //generated by Mailtrap
        }
    });
    transporter.sendMail(message, (err) => {
        if (err) {
            return err;
        }
        return true;
    });

    /* transporter.sendMail(message, (err, info) => {
      if (err) {
        return false;
      }
      // console.log(info);
      // console.log('Message sent: %s', info.messageId);
      // Preview only available when sending through an Ethereal account
      console.log('Preview URL: %s', nodemailer.getTestMessageUrl(info));
    }); */
};
